- src: http://github.com/websoft9dev/role_common
  version: master

- src: http://github.com/websoft9dev/role_jdk
  version: master
  
- src: http://github.com/websoft9dev/role_docker
  version: master

# 根据需求添加相对应的role

- src: http://github.com/websoft9dev/role_preend
  version: master
  
- src: http://github.com/websoft9dev/role_end
  version: master

